export const initialNodes = [
    {
      id: "horizontal-1",
      sourcePosition: "right",
      data: { label: "Input" },
      position: { x: 0, y: 300 },
      style: { visibility: "hidden" },
    },
    {
      id: "horizontal-2",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "Research",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 250, y: 100 },
    },
    {
      id: "horizontal-3",
      sourcePosition: "right",
      targetPosition: "left",
      position: { x: 250, y: 200 },
      type: "custom",
      data: {
        source: true,
        label: "Planning",
        bgColor: "#93c5fd",
        txtColor: "#334155",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
    },
    {
      id: "horizontal-4",
      sourcePosition: "right",
      targetPosition: "left",
      data: { label: "Designing" },
      position: { x: 250, y: 300 },
      type: "custom",
      data: {
        source: true,
        label: "Designing",
        bgColor: "#f97316",
        txtColor: "#334155",
        chartData: { positive: 14451, negative: 12839, comments: 11463 },
      },
    },
  
    {
      id: "horizontal-5",
      sourcePosition: "right",
      targetPosition: "left",
      position: { x: 250, y: 400 },
      type: "custom",
      data: {
        source: true,
        label: "Manufacturing",
        bgColor: "#fca5a5",
        txtColor: "#334155",
        chartData: { positive: 10151, negative: 12239, comments: 11631 },
      },
    },
    {
      id: "horizontal-6",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "Sales/Marketing",
        bgColor: "#c084fc",
        txtColor: "#334155",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 250, y: 500 },
    },
    {
      id: "horizontal-7",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "External",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 500, y: 75 },
    },
    {
      id: "horizontal-8",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "Internal",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 500, y: 125 },
    },
    {
      id: "horizontal-9",
      targetPosition: "left",
      position: { x: 500, y: 175 },
      type: "custom",
      data: {
        label: "PRD",
        bgColor: "#93c5fd",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
    },
    {
      id: "horizontal-10",
      targetPosition: "left",
      position: { x: 500, y: 225 },
      type: "custom",
      data: {
        label: "Specs",
        bgColor: "#93c5fd",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
    },
    {
      id: "horizontal-11",
      type: "output",
      targetPosition: "left",
      position: { x: 500, y: 275 },
      type: "custom",
      data: {
        label: "Hardware",
        bgColor: "#f97316",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 1445, negative: 1283, comments: 1146 },
      },
    },
    {
      id: "horizontal-12",
      type: "output",
      targetPosition: "left",
      position: { x: 500, y: 325 },
      type: "custom",
      data: {
        label: "Software",
        bgColor: "#f97316",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 1445, negative: 1283, comments: 1146 },
      },
    },
    {
      id: "horizontal-13",
      type: "output",
      targetPosition: "left",
      position: { x: 500, y: 375 },
      type: "custom",
      data: {
        label: "Material",
        bgColor: "#fca5a5",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 11151, negative: 8239, comments: 10631 },
      },
    },
    {
      id: "horizontal-14",
      type: "output",
      targetPosition: "left",
      position: { x: 500, y: 425 },
      type: "custom",
      data: {
        label: "Production",
        bgColor: "#fca5a5",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 12151, negative: 11239, comments: 10631 },
      },
    },
    {
      id: "horizontal-15",
      type: "output",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "Online",
        bgColor: "#c084fc",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 500, y: 475 },
    },
    {
      id: "horizontal-16",
      type: "output",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "Dealership",
        bgColor: "#c084fc",
        txtColor: "#334155",
        source: false,
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 500, y: 525 },
    },
    {
      id: "horizontal-17",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "B2C",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 750, y: 50 },
    },
    {
      id: "horizontal-18",
      type: "output",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "B2C",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 750, y: 100 },
    },
    // column-4
    {
      id: "horizontal-19",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "Online",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 1000, y: -25 },
    },
    {
      id: "horizontal-20",
      type: "output",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "Interview",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 1000, y: 25 },
    },
    {
      id: "horizontal-21",
      type: "output",
      targetPosition: "left",
      type: "custom",
      data: {
        label: "Public Data",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 1000, y: 75 },
    },
    {
      id: "horizontal-22",
      sourcePosition: "right",
      targetPosition: "left",
      type: "custom",
      data: {
        source: true,
        label: "Health",
        bgColor: "#1e3a8a",
        txtColor: "#f1f5f9",
        chartData: { positive: 13451, negative: 11839, comments: 10463 },
      },
      position: { x: 1000, y: 125 },
    },
    // output
    {
      id: "horizontal-23",
      type: "output",
      targetPosition: "left",
      data: { label: "Output" },
      position: { x: 1250, y: 50 },
      style: { visibility: "hidden" },
    },
  ];
  
  export const initialEdges = [
    {
      id: "horizontal-e1-2",
      source: "horizontal-1",
      type: "smoothstep",
      target: "horizontal-2",
      animated: true,
    },
    {
      id: "horizontal-e1-3",
      source: "horizontal-1",
      type: "smoothstep",
      target: "horizontal-3",
      animated: true,
    },
    {
      id: "horizontal-e1-4",
      source: "horizontal-1",
      type: "smoothstep",
      target: "horizontal-4",
      animated: true,
      // label: "edge label",
    },
    {
      id: "horizontal-e1-5",
      source: "horizontal-1",
      type: "smoothstep",
      target: "horizontal-5",
      animated: true,
    },
    {
      id: "horizontal-e1-6",
      source: "horizontal-1",
      type: "smoothstep",
      target: "horizontal-6",
      animated: true,
    },
    {
      id: "horizontal-e2-7",
      source: "horizontal-2",
      type: "smoothstep",
      target: "horizontal-7",
      animated: true,
    },
    {
      id: "horizontal-e2-8",
      source: "horizontal-2",
      type: "smoothstep",
      target: "horizontal-8",
      animated: true,
    },
    {
      id: "horizontal-e3-9",
      source: "horizontal-3",
      type: "smoothstep",
      target: "horizontal-9",
      animated: true,
    },
    {
      id: "horizontal-e3-10",
      source: "horizontal-3",
      type: "smoothstep",
      target: "horizontal-10",
      animated: true,
    },
    {
      id: "horizontal-e4-11",
      source: "horizontal-4",
      type: "smoothstep",
      target: "horizontal-11",
      animated: true,
    },
    {
      id: "horizontal-e4-12",
      source: "horizontal-4",
      type: "smoothstep",
      target: "horizontal-12",
      animated: true,
    },
    {
      id: "horizontal-e5-13",
      source: "horizontal-5",
      type: "smoothstep",
      target: "horizontal-13",
      animated: true,
    },
    {
      id: "horizontal-e5-14",
      source: "horizontal-5",
      type: "smoothstep",
      target: "horizontal-14",
      animated: true,
    },
    {
      id: "horizontal-e6-15",
      source: "horizontal-6",
      type: "smoothstep",
      target: "horizontal-15",
      animated: true,
    },
    {
      id: "horizontal-e6-16",
      source: "horizontal-6",
      type: "smoothstep",
      target: "horizontal-16",
      animated: true,
    },
    {
      id: "horizontal-e7-17",
      source: "horizontal-7",
      type: "smoothstep",
      target: "horizontal-17",
      animated: true,
    },
    {
      id: "horizontal-e7-18",
      source: "horizontal-7",
      type: "smoothstep",
      target: "horizontal-18",
      animated: true,
    },
    // column-4
    {
      id: "horizontal-e17-19",
      source: "horizontal-17",
      type: "smoothstep",
      target: "horizontal-19",
      animated: true,
    },
    {
      id: "horizontal-e17-20",
      source: "horizontal-17",
      type: "smoothstep",
      target: "horizontal-20",
      animated: true,
    },
    {
      id: "horizontal-e17-21",
      source: "horizontal-17",
      type: "smoothstep",
      target: "horizontal-21",
      animated: true,
    },
    {
      id: "horizontal-e17-22",
      source: "horizontal-17",
      type: "smoothstep",
      target: "horizontal-22",
      animated: true,
    },
    // output
    {
      id: "horizontal-e19-23",
      source: "horizontal-19",
      type: "smoothstep",
      target: "horizontal-23",
      animated: true,
    },
    {
      id: "horizontal-e22-23",
      source: "horizontal-22",
      type: "smoothstep",
      target: "horizontal-23",
      animated: true,
    },
  ];